#pragma once

#define RGBLIGHT_EFFECT_TWINKLE

#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_TWINKLE + 3
#define RGBLIGHT_DEFAULT_ON true
#define RGBLIGHT_SPLIT
#define RGBLIGHT_SLEEP
#undef RGBLIGHT_LIMIT_VAL
#define RGBLIGHT_LIMIT_VAL 0

#define WS2812_DRIVER_REQUIRED yes

// #define CUSTOM_RGB_LAYERS