CONSOLE_ENABLE = no
DYNAMIC_TAPPING_TERM_ENABLE = no
ENCODER_ENABLE = yes
MOUSEKEY_ENABLE = yes
DYNAMIC_MACRO_ENABLE = no
OLED_ENABLE = yes

RGBLIGHT_ENABLE = yes
WS2812_DRIVER_REQUIRED = yes

SRC += features/my_leds.c
SRC += features/encoders.c